# Generated by Django 4.2 on 2023-04-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_id', models.IntegerField()),
                ('o_name', models.CharField(max_length=50)),
                ('o_price', models.FloatField()),
                ('o_date', models.DateField()),
                ('product', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('add', models.CharField(max_length=200)),
            ],
        ),
    ]
